dist: trusty

sudo: required

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov pytest-cov black pydocstyle

script:
  - pytest test/ -v --cov=./
  - make check

after_success:
- codecov
