sudo: false

language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov

script:
  - pytest test/ -v --cov=./

after_success:
- codecov --token=cc44d176-bd24-4e2a-9458-cce54bcd777e
