language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov

script:
  - pytest test/ -v --cov=./

after_success:
- codecov
